# Generated by Django 5.0.7 on 2024-08-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeadPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nel_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_cali', models.BooleanField()),
                ('bead_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='plates.beadplate')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='plates.run')),
            ],
        ),
    ]
