# Generated by Django 5.0.7 on 2024-08-02 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cali_plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrates_results', to='plates.plate')),
                ('sample_plates', models.ManyToManyField(related_name='results', to='plates.plate')),
            ],
        ),
    ]
